### ISSUE TITLE
Взятие на проходе 

### ISSUE THREAD

**Issue by ellenord** [DmitriySidyakin/Chess#1]
[Взятие на проходе](https://ru.wikipedia.org/wiki/%D0%92%D0%B7%D1%8F%D1%82%D0%B8%D0%B5_%D0%BD%D0%B0_%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4%D0%B5) не реализовано.

![изображение](https://user-images.githubusercontent.com/107148095/235831942-1878c6ef-1f7e-455e-894f-0ea951d66932.png)

**Comment by DmitriySidyakin** [comment]
Это не по правилам шахмат или эта функция не будет реализована.

**Comment by DmitriySidyakin** [comment]
Если вы по поводу ИИ, то я только что исправил баги в ИИ, но персональные компьютеры его не тянут, он был не реализован и ходило случайно, теперь в ветке main есть правильный ИИ с глубиной поиска в графе = 5.

**Comment by DmitriySidyakin** [comment]
В дальнейшем планируется, сделать простое машинное обучение для компьютерного игрока. Пока наслаждайтесь игрой между игроками с семьёй и друзьями за одним компьютером!
